# This is the default settings file. You should never edit this.

# Server setup
filePathBase="homedir"
serverKeyPath="./private.key"
certPath="./certificate.crt"
httpsPort="8443"
tokenPrivateKeyPath="./.ssh/id_rsa"
tokenTTL="24h"
saltRounds="10"
# Wiki location settings
# Relative wiki paths are relative to this
# if this is set to 'homedir' than it uses the current user home folder as the
# base of relative paths. Otherwise it needs to be an absolute path.
wikiPathBase="homedir"
# The folder that holds the wikis
wikisPath="./Wikis"
# The folder that holds the plugins
pluginsPath="./Plugins"
# The folder that holds the themes
themesPath="./Themes"
# This is the name of the wiki to use as the root wiki.
rootWikiName="IndexWiki"
# Settings for wiki access
[wikis]
  [wikis.RootWiki]
    # If this has a name that the person named is the owner and gets owner
    # privileges
    owner=false
    # If this is true than the wiki is publicly viewable as a static wiki
    public=true
    [wikis.RootWiki.access]
      Guest=["view"]
      Normal=["view", "edit"]
      Admin=["view", "edit", "admin", "upload"]
[actions]
  # These are the actions needed to be able to view a wiki and get updates
  view=["browserTiddlerList", "test", "ping", "pong", "ack"]
  # These are the actions needed to edit a wiki
  edit=["saveTiddler", "cancelEditingTiddler", "clearStatus", "deleteTiddler", "editingTiddler", "ack"]
  # These are general admin actions
  admin=["addWiki", "saveSettings", "shutdownServer", "updateRoutes", "buildHTMLWiki", "newWikiFromTiddlers", "createNewWiki", "restartServer", "unloadWiki", "ack"]
  # Scripts is special because it lets you run shell scripts. Be careful with
  # this one!
  scripts=["runScript"]
  # Owner is a special class that applies to the person who made the wiki.
  # Even if they don't belong to any groups they have special permissions for
  # that wiki.
  owner=["browserTiddlerList", "test", "ping", "pong", "saveTiddler", "cancelEditingTiddler", "clearStatus", "deleteTiddler", "editingTiddler", "unloadWiki", "ack"]
  # Uploads are done using http(s) so there don't need to be any actions listed here.
  upload=[]
